// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLOkoYOX_2hGIlrhQlrkFL5EyeDzhP7Q',
    appId: '1:873816488594:web:8ff286d9aba966e1a4844b',
    messagingSenderId: '873816488594',
    projectId: 'flutter-app-b87c9',
    authDomain: 'flutter-app-b87c9.firebaseapp.com',
    storageBucket: 'flutter-app-b87c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsMSMVkG9WN33xfAgzjpxLAVh0T0Gbq3Q',
    appId: '1:873816488594:android:2a1658a5c605dbc0a4844b',
    messagingSenderId: '873816488594',
    projectId: 'flutter-app-b87c9',
    storageBucket: 'flutter-app-b87c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQ-Pf2BDLkoqZqcS3dtejuzKxg0vp22A',
    appId: '1:873816488594:ios:fb19b0f0bd486ac5a4844b',
    messagingSenderId: '873816488594',
    projectId: 'flutter-app-b87c9',
    storageBucket: 'flutter-app-b87c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQ-Pf2BDLkoqZqcS3dtejuzKxg0vp22A',
    appId: '1:873816488594:ios:fb19b0f0bd486ac5a4844b',
    messagingSenderId: '873816488594',
    projectId: 'flutter-app-b87c9',
    storageBucket: 'flutter-app-b87c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLOkoYOX_2hGIlrhQlrkFL5EyeDzhP7Q',
    appId: '1:873816488594:web:f8abad343fef0ff1a4844b',
    messagingSenderId: '873816488594',
    projectId: 'flutter-app-b87c9',
    authDomain: 'flutter-app-b87c9.firebaseapp.com',
    storageBucket: 'flutter-app-b87c9.firebasestorage.app',
  );
}
